version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.12.6
    # 0.11.5 --> TO use custom ports for each service
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=ec2,s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - secrets/compose-common.env
